name: audio_service_example
description: Demonstrates how to use the audio_service plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.7
  logger: ^1.0.0
  provider: ^5.0.0
  http: ^0.13.0
  adaptive_navigation: ^0.0.3
  collection: ^1.15.0
  path_to_regexp: ^0.4.0
  quiver: ^3.0.0
  url_launcher: ^6.0.0
  url_strategy: ^0.2.0
  path_provider: ^2.0.1
  audio_session: ^0.1.7
  just_audio: ^0.9.24
  flutter_tts: ^3.3.3
  device_info_plus: ^3.2.1
  android_content_provider: ^0.2.0
  permission_handler : ^8.3.0
  rxdart: ^0.27.2
  audio_service: ^0.18.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true